### ISSUE TITLE
Add license to new files 

### ISSUE THREAD

**Issue by echevrier** [encointer/community-sidechain#4]
See //todo: add license in repo

**Comment by echevrier** [comment]
@clangenb Which one?

**Comment by clangenb** [comment]
Apache-2

**Comment by clangenb** [comment]
Depends:

1. The overall repository is licenced by Encointer Association.
2. Files that are added by encointer shall be licenced by the Encointer Association.
3. Files that have not been changed should be licenced according to your description.
4. Files that are coming from upstream, but have been changed by us, shall extend your description by adding the Encointer Association to the parties.
